import type { Product, Category, Brand } from "./types"

// Generate mock product data
export const featuredProducts: Product[] = [
  {
    id: "p1",
    name: "N5 CHANEL EAU DE PARFUM",
    description: "perfume",
    price: 29.99,
    discount: 0,
    brand: "Channel",
    category: "men",
    images: ["/CHANELN5.jpg", "/placeholder.svg?height=400&width=400"],
    colors: ["Black", "White", "Navy"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["t-shirt", "cotton", "casual"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    featured: true,
  },
  {
    id: "p2",
    name: "DOLCE & GABANA",
    description: "a perfume.",
    price: 59.99,
    discount: 15,
    brand: "DOLCE & GABANA",
    category: "men",
    images: ["/DOLCE_GABANA.jpg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Blue", "Black", "Gray"],
    sizes: ["30", "32", "34", "36"],
    tags: ["jeans", "denim", "slim fit"],
    rating: 4.3,
    reviews: 95,
    inStock: true,
    featured: true,
  },
  {
    id: "p3",
    name: "CHANNEL BLEU",
    description: "A perfume.",
    price: 49.99,
    discount: 0,
    brand: "CHANNEL",
    category: "women",
    images: ["/BLEU.jpg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Blue", "Pink", "Yellow"],
    sizes: ["XS", "S", "M", "L"],
    tags: ["dress", "summer", "floral"],
    rating: 4.7,
    reviews: 156,
    inStock: true,
    featured: true,
  },
  {
    id: "p4",
    name: "Leather Crossbody Bag",
    description: "A stylish and practical leather crossbody bag for everyday use.",
    price: 79.99,
    discount: 0,
    brand: "Urban Carry",
    category: "accessories",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Brown", "Black", "Tan"],
    sizes: ["One Size"],
    tags: ["bag", "leather", "crossbody"],
    rating: 4.8,
    reviews: 112,
    inStock: true,
    featured: true,
  },
  {
    id: "p5",
    name: "Wireless Bluetooth Earbuds",
    description: "High-quality wireless earbuds with noise cancellation.",
    price: 129.99,
    discount: 20,
    brand: "SoundTech",
    category: "technology",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Black", "White"],
    sizes: ["One Size"],
    tags: ["earbuds", "wireless", "bluetooth"],
    rating: 4.6,
    reviews: 89,
    inStock: true,
    featured: true,
  },
  {
    id: "p6",
    name: "Running Shoes",
    description: "Lightweight and comfortable running shoes with excellent support.",
    price: 119.99,
    discount: 0,
    brand: "AthleteFirst",
    category: "shoes",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Black/Red", "Blue/White", "Gray/Yellow"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    tags: ["shoes", "running", "athletic"],
    rating: 4.4,
    reviews: 76,
    inStock: true,
    featured: true,
  },
  {
    id: "p7",
    name: "Moisturizing Face Cream",
    description: "Hydrating face cream suitable for all skin types.",
    price: 34.99,
    discount: 10,
    brand: "NaturalGlow",
    category: "beauty",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["One Color"],
    sizes: ["50ml", "100ml"],
    tags: ["skincare", "face cream", "moisturizer"],
    rating: 4.9,
    reviews: 203,
    inStock: true,
    featured: true,
  },
  {
    id: "p8",
    name: "Smart Watch",
    description: "Feature-packed smart watch with health monitoring and notifications.",
    price: 199.99,
    discount: 15,
    brand: "TechWear",
    category: "technology",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: ["One Size"],
    tags: ["watch", "smart watch", "wearable"],
    rating: 4.5,
    reviews: 167,
    inStock: true,
    featured: true,
  },
  {
    id: "p9",
    name: "Leather Wallet",
    description: "Genuine leather wallet with multiple card slots and RFID protection.",
    price: 49.99,
    discount: 0,
    brand: "Urban Carry",
    category: "accessories",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Brown", "Black"],
    sizes: ["One Size"],
    tags: ["wallet", "leather", "accessories"],
    rating: 4.7,
    reviews: 92,
    inStock: true,
    featured: true,
  },
  {
    id: "p10",
    name: "Silk Scarf",
    description: "Elegant silk scarf with a beautiful pattern.",
    price: 39.99,
    discount: 0,
    brand: "Bloom Fashion",
    category: "accessories",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Blue/Gold", "Red/Black", "Green/White"],
    sizes: ["One Size"],
    tags: ["scarf", "silk", "accessories"],
    rating: 4.6,
    reviews: 58,
    inStock: true,
    featured: true,
  },
  {
    id: "p11",
    name: "Wireless Headphones",
    description: "Over-ear wireless headphones with premium sound quality.",
    price: 149.99,
    discount: 20,
    brand: "SoundTech",
    category: "technology",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["Black", "Silver"],
    sizes: ["One Size"],
    tags: ["headphones", "wireless", "audio"],
    rating: 4.8,
    reviews: 143,
    inStock: true,
    featured: true,
  },
  {
    id: "p12",
    name: "Casual Sneakers",
    description: "Stylish and comfortable casual sneakers for everyday wear.",
    price: 69.99,
    discount: 0,
    brand: "StreetStyle",
    category: "shoes",
    images: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    colors: ["White", "Black", "Gray"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    tags: ["sneakers", "casual", "shoes"],
    rating: 4.5,
    reviews: 87,
    inStock: true,
    featured: true,
  },
]

// Generate more products by combining the featured ones with variations
export const allProducts: Product[] = [
  ...featuredProducts,
  ...featuredProducts.map((product, index) => ({
    ...product,
    id: `p${index + 13}`,
    name: `${product.name} - Limited Edition`,
    price: product.price * 1.2,
    discount: Math.random() > 0.5 ? Math.floor(Math.random() * 30) : 0,
    featured: Math.random() > 0.7,
  })),
]

// Categories
export const categories: Category[] = [
  {
    id: "c1",
    name: "Men",
    slug: "men",
    image: "/placeholder.svg?height=400&width=400",
    description: "Men's clothing and accessories",
  },
  {
    id: "c2",
    name: "Women",
    slug: "women",
    image: "/placeholder.svg?height=400&width=400",
    description: "Women's clothing and accessories",
  },
  {
    id: "c3",
    name: "Beauty",
    slug: "beauty",
    image: "/placeholder.svg?height=400&width=400",
    description: "Skincare, makeup, and beauty products",
  },
  {
    id: "c4",
    name: "Technology",
    slug: "technology",
    image: "/placeholder.svg?height=400&width=400",
    description: "Gadgets, electronics, and tech accessories",
  },
  {
    id: "c5",
    name: "Accessories",
    slug: "accessories",
    image: "/placeholder.svg?height=400&width=400",
    description: "Bags, wallets, jewelry, and more",
  },
  {
    id: "c6",
    name: "Shoes",
    slug: "shoes",
    image: "/placeholder.svg?height=400&width=400",
    description: "Footwear for all occasions",
  },
]

// Brands
export const brands: Brand[] = [
  {
    id: "b1",
    name: "BCS Essentials",
    logo: "/placeholder.svg?height=200&width=200",
    description: "High-quality basics for everyday wear",
  },
  {
    id: "b2",
    name: "Denim Co.",
    logo: "/placeholder.svg?height=200&width=200",
    description: "Premium denim products with modern styling",
  },
  {
    id: "b3",
    name: "Bloom Fashion",
    logo: "/placeholder.svg?height=200&width=200",
    description: "Trendy and feminine fashion for the modern woman",
  },
  {
    id: "b4",
    name: "Urban Carry",
    logo: "/placeholder.svg?height=200&width=200",
    description: "Stylish and functional bags and accessories",
  },
  {
    id: "b5",
    name: "SoundTech",
    logo: "/placeholder.svg?height=200&width=200",
    description: "Innovative audio products with superior sound quality",
  },
  {
    id: "b6",
    name: "AthleteFirst",
    logo: "/placeholder.svg?height=200&width=200",
    description: "Performance sportswear for serious athletes",
  },
]

